import {
  existsSync,
  mkdirSync,
  rmSync,
  symlinkSync,
  writeFileSync,
} from "node:fs";
import { dirname, relative, resolve } from "node:path";

const root = resolve(import.meta.dir, "..");
const pocketjs = resolve(root, "vendor/pocketjs");
if (!existsSync(resolve(pocketjs, "package.json"))) {
  throw new Error("Pocket Desktop setup: initialize vendor/pocketjs first");
}

const links = new Map<string, string>([
  ["node_modules/@pocketjs/framework", "vendor/pocketjs"],
  ["node_modules/@types/bun", "vendor/pocketjs/node_modules/@types/bun"],
  [
    "node_modules/@types/opentype.js",
    "vendor/pocketjs/node_modules/@types/opentype.js",
  ],
  ["node_modules/opentype.js", "vendor/pocketjs/node_modules/opentype.js"],
  ["node_modules/typescript", "vendor/pocketjs/node_modules/typescript"],
  ["node_modules/solid-js", "vendor/pocketjs/node_modules/solid-js"],
]);

for (const [destination, source] of links) {
  const destinationPath = resolve(root, destination);
  const sourcePath = resolve(root, source);
  if (!existsSync(sourcePath)) {
    throw new Error(`Pocket Desktop setup: missing ${source}; run bun install in vendor/pocketjs`);
  }
  mkdirSync(dirname(destinationPath), { recursive: true });
  rmSync(destinationPath, { recursive: true, force: true });
  symlinkSync(relative(dirname(destinationPath), sourcePath), destinationPath, "dir");
}

const generatedStyles = resolve(
  pocketjs,
  "framework/src/styles.generated.ts",
);
if (!existsSync(generatedStyles)) {
  writeFileSync(
    generatedStyles,
    "// Generated by PocketJS builds.\nexport const STYLE_IDS: Record<string, number> = {};\n",
  );
}

console.log("Pocket Desktop setup: PocketJS and SolidJS links ready");
